### ISSUE TITLE
Update toolchain to load GLSL for Shaders rather than use inline strings.

### ISSUE THREAD

**Issue by phtaylor** [ZeaInc/zea-engine#359]
Instead of using this...
```
 constructor(gl) {
    super(gl)
    this.setShaderStage(
      'VERTEX_SHADER',
      `
precision highp float;
attribute vec4 positions;
instancedattribute float instanceIds;
uniform mat4 viewMatrix;
uniform mat4 projectionMatrix;
uniform mat4 cameraMatrix;
<%include file="GLSLUtils.glsl"/>
```

We should use 

import { vertexGLSL } from './BoundingBoxShaderVertexGLSL'
import { fragmentGLSL } from './BoundingBoxShaderFragmentGLSL'

```
 constructor(gl) {
    super(gl)
    this.setShaderStage('VERTEX_SHADER', vertexGLSL)
```

**Comment by seijiwjs** [comment]
This now works. https://github.com/ZeaInc/zea-engine/tree/shader-toolchain-updates

I'll begin transitioning all inline shaders to external glsl files.

**Comment by seijiwjs** [comment]
Just logging some more progress! It looks like everything is working after transitioning all of the shader classes to use external glsl files. All of the new files are under Shaders/GLSLFiles -- will be much nicer to work with!

**Comment by seijiwjs** [comment]
All glsl template literals look to be moved to external glsl files! The GLSL folder, where the glsl snippets are stored, is pretty messy, it could be refactored. Would one file with all the SetShaderModule() calls be good? Also, all the snippets could have their own directory.
