### ISSUE TITLE
Zoom to Fit

### ISSUE THREAD

**Issue by raffdp** [ZeaInc/zea-engine#369]
API call to:

Zoom to fit the entire scene bounding box
Zoom to fit the selected object's bounding box

**Comment by phtaylor** [comment]
Hi there, thanks for logging an issue. In fact both of these.methids are available. FrameView will vfit the viewpoint to an array of items passed in, and frameAll will fit the entire scene into the active viewports.(usually just one).

Note: I will keep this issue open to improve the docs.
https://docs.zea.live/zea-engine/#/api/Renderer/GLViewport?id=frameview

https://docs.zea.live/zea-engine/#/api/Renderer/GLBaseRenderer?id=frameall
