### ISSUE TITLE
Cannot rotate on iPad after tapping on model

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zea-engine#372]
**Describe the bug**
Using Chrome on an iPad I can get into a state where I can no longer rotate. It seems to happen after I select a part of the model by tapping on it, and then pan. After I pan I cannot rotate.

This didn't seem to happen on my Android phone, only on iPad.

**To Reproduce**
1. Go to https://svelte-template.zea.live/ in Chrome on an iPad
2. Tap on part of the model to select it
![image](https://user-images.githubusercontent.com/49651841/114057509-3ba2c880-9858-11eb-913c-948b759fb034.png)

3. Pan with two fingers
4. Try to rotate with one finger and you cannot

**Expected behavior**
I expected to be able to rotate.

**Tablet:**
 - Device: iPad (8th Generation)
 - OS: iPad OS 14.4.2
 - Browser: Chrome
 - Version: 87.0.4280.77
 
 **Other notes:**

> Ok, its probably not detecting a touch end event. This is a bug in the engine I expect. Please log a bug and I'll get to it. Thanks. Put the bug straight into to April milestone - Phil

**Comment by phtaylor** [comment]
Fixed.
