### ISSUE TITLE
Create a React tutorial that covers integrating a tree view.

### ISSUE THREAD

**Issue by seijiwjs** [ZeaInc/zea-engine#525]
The tree view should be able to select objects within the scene and objects selected through other methods should be highlighted in the tree view. 

The tree view should be made with React. 
- looks good
- visibility option for objects

**Comment by harley1968** [comment]
Is there any ETA on this? thanks

**Comment by seijiwjs** [comment]
Hi, 
The React tutorial can be found in the new docs [here](https://github.com/ZeaInc/zea-engine-react-tutorial).
There is now a repo that contains the end result of the tutorial [here](https://github.com/ZeaInc/zea-engine-react-tutorial)
Note: the tutorial ended up not covering the visibility option and uses a generic tree view.

Let me know if you have any further questions.
Thanks!
