### ISSUE TITLE
Canvas keeps growing breaking the DOM layout.

### ISSUE THREAD

**Issue by phtaylor** [ZeaInc/zea-engine#541]
**Describe the bug**
I have implemented an e2e test that highlights this behavior. 
http://localhost:8005/testing-e2e/layout.html

Can we fix our renderer to not break this layout.

**Comment by mauroporras** [comment]
@phtaylor checkout this commit please https://github.com/ZeaInc/zea-engine/pull/540/commits/2de1c3d3855e9b0108ae274cc4f000e10d327f2f

**Comment by mauroporras** [comment]
Closed here https://github.com/ZeaInc/zea-engine/commit/18b8a90d4b9da50e232dccc5d10cb1f8e773d5db
