### ISSUE TITLE
Crash when removing all children from existing scene

### ISSUE THREAD

**Issue by harley1968** [ZeaInc/zea-engine#551]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'childAdded')is.

**To Reproduce**
1. Load scene
2. call scene.getRoot().removeAllChildren();

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1976317/141177619-fe144032-ee74-441b-8696-08a36a7192f8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by phtaylor** [comment]
This issue has been cleaned up in the latest version of the engine.
We would recommend updating to the latest version to address this issue. 

The latest version is now implemented in TypeScript.

**Comment by phtaylor** [comment]
This is now resolved.
