### ISSUE TITLE
Control frame in zcad file missing data.

### ISSUE THREAD

**Issue by CDS15** [ZeaInc/zea-engine#709]
To Duplicate:
Process the attached file "nist_ftc_08_asme1_rc_nx1200_rb.prt" to zcad using the Zea bridge.  Take a look at the file in 3DScript and particularly this control frame:

![image](https://user-images.githubusercontent.com/98981420/159373178-95f9a451-ad11-4821-87bf-ebd34802d47b.png)

Now open the zcad version of this file in standard zcad viewer (https://cad-viewer-staging.zea.live/?).  Rotate the file around and inspect this same control frame.  Notice the missing flatness symbols & numerical data:

![image](https://user-images.githubusercontent.com/98981420/159373367-75f240f0-cad4-4cc8-8778-714608f334b3.png)

[nist_ftc_08_asme1_rc_nx1200_rb.zip](https://github.com/ZeaInc/zea-engine/files/8319557/nist_ftc_08_asme1_rc_nx1200_rb.zip)

If we can resolve this or determine if it's on the side of the Zea bridge then we can resolve it and demo to the customer.

Thanks!

Craig

**Comment by phtaylor** [comment]
I noticed these missing symbols in our call with them 
From my understanding, this is actually an issue with the bridge.

**Comment by PhilippeChevreau** [comment]
The missing .015 tolerance doesn't make sense to me, and I think it's an issue with the viewer.
As far as I can tell debugging the bridge, all the necessary mesh data for the .015 text is properly added and present in the final zcad file, just like any other text. I have no idea why it's not displayed in the viewer.

The 2 missing flatness symbols are indeed an issue with the text stroker used in Interop.

**Comment by phtaylor** [comment]
ok, I will isolate this geometry and take a good look at it. thanks

**Comment by phtaylor** [comment]
I think we can resolve this issue.


I was focusing on the flatness symbol, which Philippe has explained, and the numeric values show up fine for me. 

![image](https://user-images.githubusercontent.com/840121/160713120-8c668e8d-0bee-4e11-ae0c-af6e5a9fdd71.png)

![image](https://user-images.githubusercontent.com/840121/160713309-e17e80ad-74f4-45a2-b6b0-751a63aab228.png)

**Comment by CDS15** [comment]
Works for me.  Yes, the flatness symbols are logged as our issue.  I'll close this out now...
