### ISSUE TITLE
Loading failure and Misplaced parts on Huawei devices

### ISSUE THREAD

**Issue by ConstLU** [ZeaInc/zea-engine#738]
Reproduced by opening zcad file on https://cad-viewer-staging.zea.live/? on Huawei&Honor devices.

Behaviors of two files on different devices:

![20220421-170422-490_EXCEL](https://user-images.githubusercontent.com/90293416/164420344-7d5618d8-3e76-4ecb-885e-dc03d7d38ca5.png)

Since it's not appropriate to share these files in public. zcad files and videos will be shared to Philip via DS filetransfer

**Comment by phtaylor** [comment]
Thanks for this data. there was a bug with pinch-to-zoom that was causing the camera to jump back.  (the camera was actually re-framing the view when a user started a 'pinch' operation. This is now fixed.)

**Comment by phtaylor** [comment]
I have been able to test on Huawei P30 device and found that there are some precision issues in the Heuawei GPU that was causing the misplaced parts.

The solution is to disable the 'multi-draw' code path for all Android GPUs. I have published an update to the https://cad-viewer-staging.zea.live/  That disabled multi-draw on all android devices. 

Would you be able to re-test and let me know if you see improvements?
I was not able to test on either Huawei P40, or Honor 30s.

**Comment by phtaylor** [comment]
This issue has been resolved.
